version: '3.8'

services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: bioskop-mysql
    restart: always
    environment:
      - TZ=Asia/Jakarta
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_member_service
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bioskop-network

  redis:
    image: redis:alpine
    platform: linux/amd64
    container_name: bioskop-redis
    restart: always
    environment:
      - TZ=Asia/Jakarta
    ports:
      - "6379:6379"
    networks:
      - bioskop-network

  # --- Database Khusus Member Service ---
  member-db:
    image: postgres:15
    container_name: member-postgres
    restart: always
    environment:
      - POSTGRES_DB=db_member_service
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    networks:
      - bioskop-network

  # --- Member Service (Sekarang menggunakan Postgres) ---
  member-service:
    build:
      context: ./member-service
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: member-service
    restart: always
    command: php artisan serve --host=0.0.0.0 --port=8001
    ports:
      - "8001:8001"
    volumes:
      - ./member-service:/var/www
      - /var/www/vendor
    environment:
      - TZ=Asia/Jakarta
      - APP_NAME=MemberService
      - APP_ENV=local
      - APP_KEY=base64:YVQ+CZu4+iVmcEDzQh2mIruuQtLtfkizbXvYGkVZrXU=
      - APP_DEBUG=true
      - APP_URL=http://localhost:8001
      - DB_CONNECTION=pgsql
      - DB_HOST=member-db
      - DB_PORT=5432
      - DB_DATABASE=db_member_service
      - DB_USERNAME=user
      - DB_PASSWORD=pass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_CONNECTION=redis
      - TICKET_SERVICE_URL=http://ticket-service:8003
    depends_on:
      - member-db
      - redis
    networks:
      - bioskop-network

  # --- Hasura Khusus Member Service ---
  hasura-member:
    image: hasura/graphql-engine:v2.30.0
    container_name: hasura-member
    restart: always
    ports:
      - "8081:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://user:pass@member-db:5432/db_member_service
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    depends_on:
      - member-db
    networks:
      - bioskop-network

  # --- Queue Worker Khusus Member Service (Redis Message Broker) ---
  member-queue-worker:
    build:
      context: ./member-service
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: member-queue-worker
    restart: always
    command: php artisan queue:work redis --sleep=3 --tries=3
    volumes:
      - ./member-service:/var/www
      - /var/www/vendor
    environment:
      - TZ=Asia/Jakarta
      - APP_NAME=MemberService
      - APP_ENV=local
      - APP_KEY=base64:YVQ+CZu4+iVmcEDzQh2mIruuQtLtfkizbXvYGkVZrXU=
      - DB_CONNECTION=pgsql
      - DB_HOST=member-db
      - DB_PORT=5432
      - DB_DATABASE=db_member_service
      - DB_USERNAME=user
      - DB_PASSWORD=pass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_CONNECTION=redis
    depends_on:
      - member-db
      - redis
      - member-service
    networks:
      - bioskop-network

  movie-service:
    build:
      context: ./movie-service
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: movie-service
    restart: always
    command: php artisan serve --host=0.0.0.0 --port=8002
    ports:
      - "8002:8002"
    environment:
      - TZ=Asia/Jakarta
      - APP_NAME=MovieService
      - APP_ENV=local
      - APP_KEY=base64:I08dTdYnUOyQFiiwKd4d1pOEqa3TGfsReUKGQ5bnpT8=
      - APP_DEBUG=true
      - APP_URL=http://localhost:8002
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=db_movie_service
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_CONNECTION=redis
      - TICKET_SERVICE_URL=http://ticket-service:8003
    depends_on:
      - mysql
      - redis
    networks:
      - bioskop-network

  # --- Database Khusus Ticket Service ---
  ticket-db:
    image: postgres:15
    container_name: ticket-postgres
    restart: always
    environment:
      - POSTGRES_DB=db_ticket_service
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    networks:
      - bioskop-network

  # --- Ticket Service (Sekarang menggunakan Postgres) ---
  ticket-service:
    build:
      context: ./ticket-service
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: ticket-service
    restart: always
    command: php artisan serve --host=0.0.0.0 --port=8003
    ports:
      - "8003:8003"
    volumes:
      - ./ticket-service:/var/www
      - /var/www/vendor
    environment:
      - TZ=Asia/Jakarta
      - APP_NAME=TicketService
      - APP_ENV=local
      - APP_KEY=base64:w3Kitd9iVTcAAFH8ZsJR8EFS17xFOLHthRORDRX/7pg=
      - APP_DEBUG=true
      - APP_URL=http://localhost:8003
      - DB_CONNECTION=pgsql
      - DB_HOST=ticket-db
      - DB_PORT=5432
      - DB_DATABASE=db_ticket_service
      - DB_USERNAME=user
      - DB_PASSWORD=pass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_CONNECTION=redis
      - MEMBER_SERVICE_URL=http://member-service:8001
      - MOVIE_SERVICE_URL=http://movie-service:8002
    depends_on:
      - ticket-db
      - redis
    networks:
      - bioskop-network

  # --- Hasura (Sekarang Terhubung ke Postgres, pasti sukses) ---
  hasura:
    image: hasura/graphql-engine:v2.30.0
    container_name: hasura-ticket
    restart: always
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://user:pass@ticket-postgres:5432/db_ticket_service
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    depends_on:
      - ticket-db
    networks:
      - bioskop-network

  queue-worker:
    build:
      context: ./ticket-service
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: queue-worker
    restart: always
    command: php artisan queue:work redis --sleep=3 --tries=3
    volumes:
      - ./ticket-service:/var/www
      - /var/www/vendor
    environment:
      - TZ=Asia/Jakarta
      - APP_NAME=QueueWorker
      - APP_ENV=local
      - APP_KEY=base64:w3Kitd9iVTcAAFH8ZsJR8EFS17xFOLHthRORDRX/7pg=
      - DB_CONNECTION=pgsql
      - DB_HOST=ticket-db
      - DB_PORT=5432
      - DB_DATABASE=db_ticket_service
      - DB_USERNAME=user
      - DB_PASSWORD=pass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_CONNECTION=redis
      - MEMBER_SERVICE_URL=http://member-service:8001
      - MOVIE_SERVICE_URL=http://movie-service:8002
    depends_on:
      - ticket-db
      - redis
      - ticket-service
    networks:
      - bioskop-network

volumes:
  mysql_data:

networks:
  bioskop-network:
    driver: bridge